package com.harmony.shiro.auth

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {

    static nonAuthenticatedActions = [
            [controller: 'home', action: 'index']
    ]
    def filters = {
        all(uri: "/**") {
            before = {
                // Ignore direct views (e.g. the default main index page).
                if (!controllerName) return true
                if (controllerName.equals("home"))
                    return true
                // Access control by convention.
                accessControl()
            }
        }
    }
}
